#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

## CRAN packages needed for full benchmark testing
r_packages:
  - ergm
  - cwhmisc
  - laeken

## Bioconductor packages needed for full benchmark testing
bioc_packages:
  - genefilter

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: release
      r_github_packages:
        - jimhester/covr
      r_check_args: --no-codoc --no-examples --no-tests --ignore-vignettes
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env:
        - NB='w/ covr' ## Just a label
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_TESTSET_=BASE
        - _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_TESTSET_=ROW_A_SUBSET
        - _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_TESTSET_=ROW_B_SUBSET
        - _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_TESTSET_=VECTOR_SUBSET
        - _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=10;
  - if [[ "$_R_TESTSET_" == "BASE" ]]; then
      find tests/* -prune -type f   -name "*_*.R"         | xargs rm;
    elif [[ "$_R_TESTSET_" == "ROW_A_SUBSET" ]]; then
      find tests/* -prune -type f ! -name "row*_subset.R" | xargs rm;
      find tests/* -prune -type f   -name "row*Var*_subset.R" | xargs rm;
    elif [[ "$_R_TESTSET_" == "ROW_B_SUBSET" ]]; then
      find tests/* -prune -type f ! -name "row*_subset.R" | xargs rm;
      find tests/* -prune -type f ! -name "row*Var*_subset.R" | xargs rm;
    elif [[ "$_R_TESTSET_" == "VECTOR_SUBSET" ]]; then
      find tests/* -prune -type f ! -name "*_subset.R" | xargs rm;
      find tests/* -prune -type f   -name "row*_subset.R" | xargs rm;
    elif [[ "$_R_TESTSET_" == "PARALLEL" ]]; then
      find tests/* -prune -type f ! -name "*_parallel.R"  | xargs rm;
    fi
  


notifications:
  email:
    on_success: change
    on_failure: change
