#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: release
      r_github_packages:
        - jimhester/covr
      r_check_args: --no-codoc --no-examples --no-tests --ignore-vignettes
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env:
        - NB='w/ covr' ## Just a label
        - _R_CHECK_FULL_=TRUE
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_CHECK_FULL_=TRUE
        - _R_TEST_=BASE
	- _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_CHECK_FULL_=TRUE
        - _R_TEST_=SUBSET
        - _R_SUBSET_TEST_=ROW_PREFIX
	- _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: release
      addons:
        apt:
          packages:
          - valgrind
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes --use-valgrind
      env:
        - NB='w/ valgrind' ## Just a label
        - _R_CHECK_FULL_=TRUE
        - _R_TEST_=SUBSET
        - _R_SUBSET_TEST_=NOT_ROW_PREFIX
	- _R_CHECK_USE_VALGRIND_=TRUE
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - if [ "$_R_TEST_" == "BASE" ]; then
      find tests/* -prune -type f -name "*_*.R" | xargs rm;
    fi
  - if [ "$_R_TEST_" == "SUBSET" ]; then
      find tests/* -prune -type f ! -name "*_subset.R" | xargs rm;
      if [ "$_R_SUBSET_TEST_" == "ROW_PREFIX" ]; then
        find tests/* -prune -type f ! -name "row*_subset.R" | xargs rm;
      else
        find tests/* -prune -type f -name "row*_subset.R" | xargs rm;
      fi;
    fi
  - if [ "$_R_TEST_" == "PARALLEL" ]; then
      find tests/* -prune -type f ! -name "*_parallel.R" | xargs rm;
    fi
  


notifications:
  email:
    on_success: change
    on_failure: change
